DELETE FROM Events;
DELETE FROM Lines;
DELETE FROM LineStations;
DELETE FROM Connections;
DELETE FROM Stations;

INSERT INTO Events (description, score) VALUES
('Quiet journey', 0),
('Wrong platform', -2),
('Kind passenger gave directions', 1),
('Train arrived immediately', 2),
('Signal failure caused delays', -3),
('Found a forgotten travel voucher', 3),
('Crowded carriage slowed you down', -1),
('Helpful station staff assisted you', 2),
('Missed the connecting train', -2),
('Express service skipped traffic', 3),
('Ticket inspection delayed everyone', -1),
('Lost some coins while rushing', -2),
('A musician brightened your trip', 1),
('Metro line partially suspended', -4),
('You found a dropped coin', 1),
('Unexpected shortcut through the station', 2),
('Escalator out of service', -1),
('Free promotional ticket', 2),
('Train stopped between stations', -3),
('Perfect connection timing', 3),
('Map was hard to read', -1),
('Friendly commuter shared advice', 1),
('Maintenance work on the line', -2),
('Fast boarding', 1),
('Lost your seat to the crowd', -1),
('Lucky transfer with no waiting', 2),
('Service disruption announced', -3),
('Station renovation caused confusion', -2),
('You took the wrong exit', -1),
('Unexpected direct connection', 3),
('Doors malfunctioned briefly', -2),
('You discovered a faster route', 2),
('A station performance lifted morale', 1),
('Severe delay on your line', -4),
('Train was nearly empty', 1),
('Helpful signs guided your route', 1),
('Missed an interchange', -2),
('Free coffee sample in the station', 1),
('Track issue reduced service', -3),
('Quick transfer at interchange', 2),
('Dropped some change', -1),
('Received a travel reward', 2),
('Heavy congestion in station corridors', -2),
('Unexpected train cancellation', -4),
('Found spare coins near a ticket machine', 2),
('Air conditioning was broken', -1),
('You boarded the perfect train', 2),
('Security check caused delay', -1),
('Excellent service throughout the journey', 3),
('Construction work blocked an entrance', -2),
('You got lost inside a large station', -2),
('Train arrived ahead of schedule', 2),
('Friendly passenger shared route tips', 1),
('Temporary line closure', -4),
('Lucky seat available during rush hour', 1),
('Transfer corridor was crowded', -1),
('Found a promotional discount code', 2),
('Unexpected waiting time', -2),
('Smooth ride across multiple lines', 3),
('You forgot which platform to use', -2),
('Staff announced a faster alternative', 2),
('Minor signal issue', -1),
('Excellent transfer timing', 2),
('You accidentally boarded the wrong train', -3),
('Station festival gave free souvenirs', 2),
('Train was delayed by technical issues', -3),
('You found extra coins in your pocket', 1),
('Broken ticket machine caused a queue', -1),
('Fast-moving crowd helped your pace', 1),
('Major service outage', -4),
('A commuter warned you of a delay', 1),
('Train doors closed just in time', 2),
('Unexpected platform change', -1),
('Perfectly synchronized connections', 3),
('Long wait for the next train', -2),
('Helpful map display updated your route', 1),
('You took a longer route by mistake', -2),
('Station staff provided excellent assistance', 2),
('Minor crowding on the train', -1),
('Lucky express train arrived', 3),
('Temporary speed restrictions', -2),
('You recovered some lost coins', 1),
('Confusing announcement over speakers', -1),
('Quick interchange between lines', 2),
('Track maintenance caused delays', -3),
('Found a metro loyalty reward', 2),
('Train skipped a scheduled stop', -2),
('Everything went according to plan', 1),
('A station guide helped you navigate', 1),
('Major power outage on the network', -4),
('Unexpected bonus from a transit promotion', 3),
('Crowded platform slowed boarding', -1),
('Train arrived exactly when needed', 2),
('You missed your stop and had to backtrack', -3),
('Helpful commuter pointed out a shortcut', 2),
('Network operating flawlessly today', 4),
('Severe disruption across multiple lines', -4),
('Lucky streak of perfect transfers', 4),
('You found a valuable transit reward', 4);


INSERT INTO Stations (station_id, name, is_interchange) VALUES
(1, 'Porta Nuova', 1),
(2, 'Re Umberto', 1),
(3, 'Vinzaglio', 1),
(4, 'Porta Susa', 1),
(5, 'XVIII Dicembre', 1),
(6, 'Principi d Acaja', 0),
(7, 'Bernini', 0),
(8, 'Racconigi', 0),
(9, 'Statuto', 1),
(10, 'Castello', 1),
(11, 'Solferino', 0),
(12, 'Vittorio Veneto', 0),
(13, 'Gran Madre', 0),
(14, 'Mole Antonelliana', 0),
(15, 'Carlo Alberto', 0),
(16, 'Palazzo Nuovo', 0),
(17, 'Cairoli', 0),
(18, 'Madama Cristina', 0),
(19, 'Marconi', 0),
(20, 'Dante', 0);

INSERT INTO Lines (line_id, name) VALUES
(1, 'M1'),
(2, 'Line 4'),
(3, 'Line 13'),
(4, 'Line 15'),
(5, 'Line 18');

-- M1
INSERT INTO LineStations VALUES
(1, 1, 1),
(1, 2, 2),
(1, 3, 3),
(1, 4, 4),
(1, 5, 5),
(1, 6, 6),
(1, 7, 7),
(1, 8, 8);

-- linea 4
INSERT INTO LineStations VALUES
(2, 5, 1),
(2, 9, 2),
(2, 10, 3),
(2, 12, 4),
(2, 13, 5);

-- linea 13
INSERT INTO LineStations VALUES
(3, 4, 1),
(3, 11, 2),
(3, 10, 3),
(3, 14, 4),
(3, 13, 5);

-- linea 15
INSERT INTO LineStations VALUES
(4, 1, 1),
(4, 15, 2),
(4, 10, 3),
(4, 16, 4),
(4, 17, 5);

-- linea 18
INSERT INTO LineStations VALUES
(5, 20, 1),
(5, 19, 2),
(5, 18, 3),
(5, 1, 4),
(5, 2, 5),
(5, 10, 6);

INSERT INTO Connections VALUES
(1,1,1,2),
(2,1,2,1),
(3,1,2,3),
(4,1,3,2),
(5,1,3,4),
(6,1,4,3),
(7,1,4,5),
(8,1,5,4),
(9,1,5,6),
(10,1,6,5),
(11,1,6,7),
(12,1,7,6),
(13,1,7,8),
(14,1,8,7),

(15,2,5,9),
(16,2,9,5),
(17,2,9,10),
(18,2,10,9),
(19,2,10,12),
(20,2,12,10),
(21,2,12,13),
(22,2,13,12),

(23,3,4,11),
(24,3,11,4),
(25,3,11,10),
(26,3,10,11),
(27,3,10,14),
(28,3,14,10),
(29,3,14,13),
(30,3,13,14),

(31,4,1,15),
(32,4,15,1),
(33,4,15,10),
(34,4,10,15),
(35,4,10,16),
(36,4,16,10),
(37,4,16,17),
(38,4,17,16),

(39,5,20,19),
(40,5,19,20),
(41,5,19,18),
(42,5,18,19),
(43,5,18,1),
(44,5,1,18),
(45,5,1,2),
(46,5,2,1),
(47,5,2,10),
(48,5,10,2);