INSERT INTO Events (description, score) VALUES
('Quiet journey', 0),
('Wrong platform', -2),
('Kind passenger gave directions', 1),
('Train arrived immediately', 2),
('Signal failure caused delays', -3),
('Found a forgotten travel voucher', 3),
('Crowded carriage slowed you down', -1),
('Helpful station staff assisted you', 2),
('Missed the connecting train', -2),
('Express service skipped traffic', 3),
('Ticket inspection delayed everyone', -1),
('Lost some coins while rushing', -2),
('A musician brightened your trip', 1),
('Metro line partially suspended', -4),
('You found a dropped coin', 1),
('Unexpected shortcut through the station', 2),
('Escalator out of service', -1),
('Free promotional ticket', 2),
('Train stopped between stations', -3),
('Perfect connection timing', 3),
('Map was hard to read', -1),
('Friendly commuter shared advice', 1),
('Maintenance work on the line', -2),
('Fast boarding', 1),
('Lost your seat to the crowd', -1),
('Lucky transfer with no waiting', 2),
('Service disruption announced', -3),
('Station renovation caused confusion', -2),
('You took the wrong exit', -1),
('Unexpected direct connection', 3),
('Doors malfunctioned briefly', -2),
('You discovered a faster route', 2),
('A station performance lifted morale', 1),
('Severe delay on your line', -4),
('Train was nearly empty', 1),
('Helpful signs guided your route', 1),
('Missed an interchange', -2),
('Free coffee sample in the station', 1),
('Track issue reduced service', -3),
('Quick transfer at interchange', 2),
('Dropped some change', -1),
('Received a travel reward', 2),
('Heavy congestion in station corridors', -2),
('Unexpected train cancellation', -4),
('Found spare coins near a ticket machine', 2),
('Air conditioning was broken', -1),
('You boarded the perfect train', 2),
('Security check caused delay', -1),
('Excellent service throughout the journey', 3),
('Construction work blocked an entrance', -2),
('You got lost inside a large station', -2),
('Train arrived ahead of schedule', 2),
('Friendly passenger shared route tips', 1),
('Temporary line closure', -4),
('Lucky seat available during rush hour', 1),
('Transfer corridor was crowded', -1),
('Found a promotional discount code', 2),
('Unexpected waiting time', -2),
('Smooth ride across multiple lines', 3),
('You forgot which platform to use', -2),
('Staff announced a faster alternative', 2),
('Minor signal issue', -1),
('Excellent transfer timing', 2),
('You accidentally boarded the wrong train', -3),
('Station festival gave free souvenirs', 2),
('Train was delayed by technical issues', -3),
('You found extra coins in your pocket', 1),
('Broken ticket machine caused a queue', -1),
('Fast-moving crowd helped your pace', 1),
('Major service outage', -4),
('A commuter warned you of a delay', 1),
('Train doors closed just in time', 2),
('Unexpected platform change', -1),
('Perfectly synchronized connections', 3),
('Long wait for the next train', -2),
('Helpful map display updated your route', 1),
('You took a longer route by mistake', -2),
('Station staff provided excellent assistance', 2),
('Minor crowding on the train', -1),
('Lucky express train arrived', 3),
('Temporary speed restrictions', -2),
('You recovered some lost coins', 1),
('Confusing announcement over speakers', -1),
('Quick interchange between lines', 2),
('Track maintenance caused delays', -3),
('Found a metro loyalty reward', 2),
('Train skipped a scheduled stop', -2),
('Everything went according to plan', 1),
('A station guide helped you navigate', 1),
('Major power outage on the network', -4),
('Unexpected bonus from a transit promotion', 3),
('Crowded platform slowed boarding', -1),
('Train arrived exactly when needed', 2),
('You missed your stop and had to backtrack', -3),
('Helpful commuter pointed out a shortcut', 2),
('Network operating flawlessly today', 4),
('Severe disruption across multiple lines', -4),
('Lucky streak of perfect transfers', 4),
('You found a valuable transit reward', 4);